# Site settings
title: 姚强的博客
email: yq15853176753@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  姚强的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://yaoqiang233.github.io/ # the base hostname & protocol for your site
rss_url: 
author: Yao Qiang

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account

weibo: hijackemmm
github: yaoqiang233

# avatar and Favicon
avatar:  http://fb.topitme.com/b/88/43/11224527285f54388bl.jpg
favicon:  http://fb.topitme.com/b/88/43/11224527285f54388bl.jpg
# disqus config
disqus:
  shortname: yaoqiang233

# google analytics config
ga:
  id: UA-112409559-1
  url: yaoqiang233.github.io

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

